"""visit external_id for yclients sync

Revision ID: 9e87767e0122
Revises: 43c6618cbd23
Create Date: 2026-05-13 15:14:22.740011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9e87767e0122'
down_revision: Union[str, Sequence[str], None] = '43c6618cbd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visits_external_id'), 'visits', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_external_id'), table_name='visits')
    op.drop_column('visits', 'external_id')
    # ### end Alembic commands ###
