// Auto-generated by main.py
    // Raised-text business card
    union() {
        // Business card body
cube([85.0, 54.0, 1.4], center=false);

        translate([2.5, 44.7, 1.4])
                    linear_extrude(height=0.6)
                        text("Третьяков Михаил Васильевич", size=6.8,
                             font="Liberation Sans:style=Bold", halign="left", valign="baseline");

        translate([2.5, 35.300000000000004, 1.4])
                    linear_extrude(height=0.6)
                        text("Юрист / Адвокат", size=5.0,
                             font="Liberation Sans:style=Bold", halign="left", valign="baseline");

        translate([2.5, 27.700000000000003, 1.4])
                    linear_extrude(height=0.6)
                        text("Тел: +79082798499", size=4.5,
                             font="Liberation Sans:style=Bold", halign="left", valign="baseline");

        translate([2.5, 20.6, 1.4])
                    linear_extrude(height=0.6)
                        text("Адрес: г. Краснокамск, ул. Геофизиков, 2/1", size=4.5,
                             font="Liberation Sans:style=Bold", halign="left", valign="baseline");

        translate([2.5, 2.5, 1.4])
                    linear_extrude(height=0.6)
                        text("Рекомендовано для: Bambu Lab A1", size=3.8,
                             font="Liberation Sans:style=Bold", halign="left", valign="baseline");
    }
